---
title: "Untitled"
output: html_document
---
```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)
library(reshape2)
```
```{r}
train<-read.csv("/Users/colleenjung/Downloads/spaceship-titanic/train.csv")
head(train)
dim(train)
```
```{r}
#drop missing values
train = train[(!apply(train == '', 1, any)), ]
# split column and add new columns to df
train=train %>% 
  drop_na()%>%
  separate('Cabin', c('Deck', 'Num', 'Side'), sep='/') %>%
  separate('PassengerId',c('group', 'people'), sep = '_') 

#train
colSums(is.na(train) | train == '')

#replace 1 or 0 to VIP, CryoSleep, Transported
train$VIP=as.numeric(as.logical(train$VIP))
train$CryoSleep=as.numeric(as.logical(train$CryoSleep))
train$Transported=as.numeric(as.logical(train$Transported))
```

```{r}
#Convert wide to long
#Small Multiple Chart
p <- train %>% 
    keep(is.numeric) %>%
    gather() %>% 
    ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram(bins = 50) 
p
table(train$HomePlanet)
table(train$Destination)
table(train$people)

table(train$Transported)
hist(as.numeric(train$group))
```
1. Viewing distribution:
2. Skewness

